version: "2.4"

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.lein
    working_dir: /app
    volumes:
      - jar-volume:/jar
      - .:/app
    command: >
      sh -c "lein uberjar &&
             cp target/metabase-flightsql-driver-0.1.0-SNAPSHOT-standalone.jar /jar/flightsql-metabase-driver.jar &&
             ls -l /jar &&
             echo 'Build complete' &&
             exit 0"
    restart: "no"



  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    depends_on:
      - builder
    volumes:
      - jar-volume:/jar
      - /dev/urandom:/dev/random:ro
    command: >
      sh -c "cp /jar/flightsql-metabase-driver.jar /plugins/flightsql-metabase-driver.jar &&
             echo 'Plugin copied, starting Metabase' &&
             exec /app/run_metabase.sh"
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: ["CMD", "curl", "--fail", "-I", "http://localhost:3000/api/health"]
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - metanet1

  spiced:
    image: spiceai/spiceai:1.0.6
    container_name: spiced-container
    privileged: true
    user: root
    volumes:
      - type: bind
        source: ./spicepod.yaml
        target: /app/spicepod.yaml
      - type: bind
        source: ./data
        target: /app/data
    command: "--http 0.0.0.0:8090 --metrics 0.0.0.0:9090 --flight 0.0.0.0:50051"
    ports:
      - "50051:50051"
      - "8090:8090"
      - "9090:9090"
    networks:
      - metanet1

networks:
  metanet1:
    driver: bridge

volumes:
  pgdata:
  jar-volume:
