FROM openjdk:11-jdk-slim

# Install curl for downloading Leiningen
RUN apt-get update && apt-get install -y curl

# Install Leiningen
RUN curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein \
    && mv lein /usr/local/bin/lein \
    && chmod +x /usr/local/bin/lein

WORKDIR /app
COPY . /app

# Build the uberjar
RUN lein uberjar
