services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      - type: bind
        source: C:\Users\DEEPGAMING\workspace\repos\metabase-flightsql-driver\target\metabase-flightsql-driver-0.1.0-SNAPSHOT-standalone.jar
        target: /plugins/flightsql-metabase-driver.jar
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - metanet1

  spiced:
    image: spiceai/spiceai:1.0.6
    container_name: spiced-container
    privileged: true
    user: root
    volumes:
      - type: bind
        source: C:\Users\DEEPGAMING\workspace\repos\metabase-flightsql-driver\spicepod.yaml
        target: /app/spicepod.yaml
      - type: bind
        source: C:\Users\DEEPGAMING\workspace\repos\metabase-flightsql-driver\data
        target: /app/data
    command: "--http 0.0.0.0:8090 --metrics 0.0.0.0:9090 --flight 0.0.0.0:50051"
    ports:
      - '50051:50051'
      - '8090:8090'
      - '9090:9090'
    networks:
      - metanet1



networks:
  metanet1:
    driver: bridge
